FROM python:3.11.3-slim

WORKDIR /app

COPY player.py .
COPY master.py .
COPY requirements.txt .
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN pip install -r requirements.txt

RUN apt-get update && apt-get install -y supervisor

EXPOSE 4000
EXPOSE 8080

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
